import type { PracticeFacts } from '@/types';

/**
 * The daily practice's reference tables (roadmap step 88).
 *
 * Questions are drawn from these at random, two entries at a time, by the
 * engine (src/engine/practice.ts). That's the point of tables rather than a
 * list of questions: the Warmup's ten are picked to be tricky, and picked
 * items are how the research literature manufactures overconfidence
 * (Gigerenzer, Hoffrage & Kleinbölting 1991; Juslin, Winman & Olsson 2000).
 * Random pairs from a reference class give easy and hard questions in their
 * natural mix, so a practice record describes the person, not the selection
 * (research/retention-2026-10.md §2.5, UI_ROADMAP D14 (c)).
 *
 * What goes in, and what stays out:
 *   - Values that don't move: coordinates, heights, diameters, years, atomic
 *     numbers, areas. No populations, no records, no "largest company".
 *   - The engine only pairs entries that differ clearly (1° of latitude, 2° of
 *     longitude, 25% in area, 5% in height or diameter, 3 years), so the
 *     small differences between sources (Mont Blanc's 4,806 or 4,808 m, a
 *     country's area with or without inland water) can never flip an answer;
 *     and not by too much (engine MAX_GAP), so few questions are giveaways.
 *     The tables are wide so that band still holds hundreds of pairs each.
 *   - No country whose area depends on a disputed border (Morocco, Pakistan,
 *     Israel, Ukraine, Cyprus, Serbia, Georgia) or on overseas territory
 *     (France, Denmark, the Netherlands, Norway). No volcano whose height
 *     changes with its eruptions (Etna).
 *
 * Sources: Wikipedia's lists as of 2026-10 (countries by area, the
 * coordinates on each city's article, the Seven Summits and the eight-
 * thousanders, the list of Solar System objects by size, each person's and
 * event's own article) and IUPAC's periodic table.
 */
export const PRACTICE_FACTS: PracticeFacts = {
  places: [
    { name: 'London', lat: 51.51, lon: -0.13 },
    { name: 'Paris', lat: 48.86, lon: 2.35 },
    { name: 'Berlin', lat: 52.52, lon: 13.4 },
    { name: 'Madrid', lat: 40.42, lon: -3.7 },
    { name: 'Rome', lat: 41.9, lon: 12.5 },
    { name: 'Lisbon', lat: 38.72, lon: -9.14 },
    { name: 'Dublin', lat: 53.35, lon: -6.26 },
    { name: 'Edinburgh', lat: 55.95, lon: -3.19 },
    { name: 'Amsterdam', lat: 52.37, lon: 4.9 },
    { name: 'Brussels', lat: 50.85, lon: 4.35 },
    { name: 'Vienna', lat: 48.21, lon: 16.37 },
    { name: 'Prague', lat: 50.08, lon: 14.44 },
    { name: 'Warsaw', lat: 52.23, lon: 21.01 },
    { name: 'Budapest', lat: 47.5, lon: 19.04 },
    { name: 'Athens', lat: 37.98, lon: 23.73 },
    { name: 'Istanbul', lat: 41.01, lon: 28.98 },
    { name: 'Moscow', lat: 55.76, lon: 37.62 },
    { name: 'Stockholm', lat: 59.33, lon: 18.07 },
    { name: 'Oslo', lat: 59.91, lon: 10.75 },
    { name: 'Helsinki', lat: 60.17, lon: 24.94 },
    { name: 'Copenhagen', lat: 55.68, lon: 12.57 },
    { name: 'Reykjavik', lat: 64.15, lon: -21.94 },
    { name: 'Venice', lat: 45.44, lon: 12.32 },
    { name: 'Barcelona', lat: 41.39, lon: 2.17 },
    { name: 'Marseille', lat: 43.3, lon: 5.37 },
    { name: 'Munich', lat: 48.14, lon: 11.58 },
    { name: 'Zurich', lat: 47.38, lon: 8.54 },
    { name: 'Cairo', lat: 30.04, lon: 31.24 },
    { name: 'Casablanca', lat: 33.57, lon: -7.59 },
    { name: 'Lagos', lat: 6.52, lon: 3.38 },
    { name: 'Nairobi', lat: -1.29, lon: 36.82 },
    { name: 'Cape Town', lat: -33.92, lon: 18.42 },
    { name: 'Johannesburg', lat: -26.2, lon: 28.05 },
    { name: 'Addis Ababa', lat: 9.03, lon: 38.74 },
    { name: 'Dakar', lat: 14.72, lon: -17.47 },
    { name: 'New York', lat: 40.71, lon: -74.01 },
    { name: 'Los Angeles', lat: 34.05, lon: -118.24 },
    { name: 'Chicago', lat: 41.88, lon: -87.63 },
    { name: 'Toronto', lat: 43.65, lon: -79.38 },
    { name: 'Montreal', lat: 45.5, lon: -73.57 },
    { name: 'Vancouver', lat: 49.28, lon: -123.12 },
    { name: 'Seattle', lat: 47.61, lon: -122.33 },
    { name: 'San Francisco', lat: 37.77, lon: -122.42 },
    { name: 'Boston', lat: 42.36, lon: -71.06 },
    { name: 'Miami', lat: 25.76, lon: -80.19 },
    { name: 'Washington, D.C.', lat: 38.91, lon: -77.04 },
    { name: 'Denver', lat: 39.74, lon: -104.99 },
    { name: 'Atlanta', lat: 33.75, lon: -84.39 },
    { name: 'Houston', lat: 29.76, lon: -95.37 },
    { name: 'New Orleans', lat: 29.95, lon: -90.07 },
    { name: 'Minneapolis', lat: 44.98, lon: -93.27 },
    { name: 'Anchorage', lat: 61.22, lon: -149.9 },
    { name: 'Honolulu', lat: 21.31, lon: -157.86 },
    { name: 'Mexico City', lat: 19.43, lon: -99.13 },
    { name: 'Havana', lat: 23.11, lon: -82.37 },
    { name: 'Bogotá', lat: 4.71, lon: -74.07 },
    { name: 'Lima', lat: -12.05, lon: -77.04 },
    { name: 'Santiago', lat: -33.45, lon: -70.67 },
    { name: 'Buenos Aires', lat: -34.6, lon: -58.38 },
    { name: 'Rio de Janeiro', lat: -22.91, lon: -43.17 },
    { name: 'São Paulo', lat: -23.55, lon: -46.63 },
    { name: 'Quito', lat: -0.18, lon: -78.47 },
    { name: 'Tokyo', lat: 35.68, lon: 139.69 },
    { name: 'Beijing', lat: 39.9, lon: 116.41 },
    { name: 'Shanghai', lat: 31.23, lon: 121.47 },
    { name: 'Hong Kong', lat: 22.32, lon: 114.17 },
    { name: 'Seoul', lat: 37.57, lon: 126.98 },
    { name: 'Bangkok', lat: 13.76, lon: 100.5 },
    { name: 'Singapore', lat: 1.35, lon: 103.82 },
    { name: 'Mumbai', lat: 19.08, lon: 72.88 },
    { name: 'Delhi', lat: 28.61, lon: 77.21 },
    { name: 'Dubai', lat: 25.2, lon: 55.27 },
    { name: 'Tehran', lat: 35.69, lon: 51.39 },
    { name: 'Jakarta', lat: -6.21, lon: 106.85 },
    { name: 'Manila', lat: 14.6, lon: 120.98 },
    { name: 'Sydney', lat: -33.87, lon: 151.21 },
    { name: 'Melbourne', lat: -37.81, lon: 144.96 },
    { name: 'Auckland', lat: -36.85, lon: 174.76 },
    { name: 'Perth', lat: -31.95, lon: 115.86 },
    { name: 'Ulaanbaatar', lat: 47.89, lon: 106.91 },
    { name: 'Kathmandu', lat: 27.72, lon: 85.32 },
    { name: 'Hanoi', lat: 21.03, lon: 105.85 },
    { name: 'Karachi', lat: 24.86, lon: 67.01 },
  ],

  // Total area, km² (land and inland water).
  countries: [
    { name: 'Russia', value: 17_098_246 },
    { name: 'Canada', value: 9_984_670 },
    { name: 'the United States', value: 9_833_520, label: 'The United States' },
    { name: 'China', value: 9_596_961 },
    { name: 'Brazil', value: 8_515_767 },
    { name: 'Australia', value: 7_692_024 },
    { name: 'India', value: 3_287_263 },
    { name: 'Argentina', value: 2_780_400 },
    { name: 'Kazakhstan', value: 2_724_900 },
    { name: 'Algeria', value: 2_381_741 },
    { name: 'DR Congo', value: 2_344_858 },
    { name: 'Saudi Arabia', value: 2_149_690 },
    { name: 'Mexico', value: 1_964_375 },
    { name: 'Indonesia', value: 1_904_569 },
    { name: 'Sudan', value: 1_886_068 },
    { name: 'Libya', value: 1_759_540 },
    { name: 'Iran', value: 1_648_195 },
    { name: 'Mongolia', value: 1_564_110 },
    { name: 'Peru', value: 1_285_216 },
    { name: 'Chad', value: 1_284_000 },
    { name: 'Niger', value: 1_267_000 },
    { name: 'Angola', value: 1_246_700 },
    { name: 'Mali', value: 1_240_192 },
    { name: 'South Africa', value: 1_221_037 },
    { name: 'Colombia', value: 1_141_748 },
    { name: 'Ethiopia', value: 1_104_300 },
    { name: 'Bolivia', value: 1_098_581 },
    { name: 'Egypt', value: 1_002_450 },
    { name: 'Tanzania', value: 947_303 },
    { name: 'Nigeria', value: 923_768 },
    { name: 'Venezuela', value: 916_445 },
    { name: 'Namibia', value: 825_615 },
    { name: 'Mozambique', value: 801_590 },
    { name: 'Chile', value: 756_102 },
    { name: 'Zambia', value: 752_618 },
    { name: 'Myanmar', value: 676_578 },
    { name: 'Afghanistan', value: 652_230 },
    { name: 'Madagascar', value: 587_041 },
    { name: 'Kenya', value: 580_367 },
    { name: 'Thailand', value: 513_120 },
    { name: 'Spain', value: 505_990 },
    { name: 'Sweden', value: 450_295 },
    { name: 'Iraq', value: 438_317 },
    { name: 'Paraguay', value: 406_752 },
    { name: 'Japan', value: 377_975 },
    { name: 'Germany', value: 357_114 },
    { name: 'Finland', value: 338_455 },
    { name: 'Vietnam', value: 331_212 },
    { name: 'Malaysia', value: 330_803 },
    { name: 'Poland', value: 312_696 },
    { name: 'Italy', value: 301_340 },
    { name: 'the Philippines', value: 300_000, label: 'The Philippines' },
    { name: 'New Zealand', value: 268_021 },
    { name: 'the United Kingdom', value: 242_495, label: 'The United Kingdom' },
    { name: 'Ghana', value: 238_533 },
    { name: 'Romania', value: 238_397 },
    { name: 'Bangladesh', value: 147_570 },
    { name: 'Nepal', value: 147_516 },
    { name: 'Greece', value: 131_957 },
    { name: 'Cuba', value: 109_884 },
    { name: 'Iceland', value: 103_000 },
    { name: 'South Korea', value: 100_210 },
    { name: 'Hungary', value: 93_030 },
    { name: 'Portugal', value: 92_212 },
    { name: 'Austria', value: 83_879 },
    { name: 'Ireland', value: 70_273 },
    { name: 'Sri Lanka', value: 65_610 },
    { name: 'Costa Rica', value: 51_100 },
    { name: 'Switzerland', value: 41_285 },
    { name: 'Belgium', value: 30_689 },
    { name: 'Qatar', value: 11_581 },
    { name: 'Jamaica', value: 10_991 },
    { name: 'Luxembourg', value: 2_586 },
    { name: 'Singapore', value: 735 },
    { name: 'Malta', value: 316 },
    { name: 'Monaco', value: 2.08 },
    { name: 'Vatican City', value: 0.49 },
  ],

  // Height above sea level, m.
  mountains: [
    { name: 'Mount Everest', value: 8849 },
    { name: 'K2', value: 8611 },
    { name: 'Kangchenjunga', value: 8586 },
    { name: 'Annapurna', value: 8091 },
    { name: 'Aconcagua', value: 6961 },
    { name: 'Chimborazo', value: 6263 },
    { name: 'Denali', value: 6190 },
    { name: 'Mount Logan', value: 5959 },
    { name: 'Kilimanjaro', value: 5895 },
    { name: 'Mount Elbrus', value: 5642 },
    { name: 'Mount Kenya', value: 5199 },
    { name: 'Mount Ararat', value: 5137 },
    { name: 'Mount Vinson', value: 4892 },
    { name: 'Mont Blanc', value: 4806 },
    { name: 'the Matterhorn', value: 4478, label: 'The Matterhorn' },
    { name: 'Mount Whitney', value: 4421 },
    { name: 'Mount Rainier', value: 4392 },
    { name: 'Pikes Peak', value: 4302 },
    { name: 'Mauna Kea', value: 4207 },
    { name: 'Mount Kinabalu', value: 4095 },
    { name: 'Mount Fuji', value: 3776 },
    { name: 'Aoraki / Mount Cook', value: 3724 },
    { name: 'the Zugspitze', value: 2962, label: 'The Zugspitze' },
    { name: 'Mount Olympus', value: 2918 },
    { name: 'Half Dome', value: 2695 },
    { name: 'Mount St. Helens', value: 2549 },
    { name: 'Mount Sinai', value: 2285 },
    { name: 'Mount Kosciuszko', value: 2228 },
    { name: 'Mount Washington', value: 1917 },
    { name: 'Ben Nevis', value: 1345 },
    { name: 'Mount Vesuvius', value: 1281 },
    { name: 'Table Mountain', value: 1085 },
  ],

  // Mean diameter, km.
  bodies: [
    { name: 'Jupiter', value: 139_820 },
    { name: 'Saturn', value: 116_460 },
    { name: 'Uranus', value: 50_724 },
    { name: 'Neptune', value: 49_244 },
    { name: 'Earth', value: 12_742 },
    { name: 'Venus', value: 12_104 },
    { name: 'Mars', value: 6_779 },
    { name: 'Ganymede', value: 5_268, label: 'Ganymede (Jupiter’s moon)' },
    { name: 'Titan', value: 5_150, label: 'Titan (Saturn’s moon)' },
    { name: 'Mercury', value: 4_879 },
    { name: 'Callisto', value: 4_821, label: 'Callisto (Jupiter’s moon)' },
    { name: 'Io', value: 3_643, label: 'Io (Jupiter’s moon)' },
    { name: 'the Moon', value: 3_475, label: 'The Moon' },
    { name: 'Europa', value: 3_122, label: 'Europa (Jupiter’s moon)' },
    { name: 'Triton', value: 2_707, label: 'Triton (Neptune’s moon)' },
    { name: 'Pluto', value: 2_377 },
    { name: 'Eris', value: 2_326, label: 'Eris (a dwarf planet)' },
    { name: 'Titania', value: 1_578, label: 'Titania (Uranus’s moon)' },
    { name: 'Rhea', value: 1_527, label: 'Rhea (Saturn’s moon)' },
    { name: 'Charon', value: 1_212, label: 'Charon (Pluto’s moon)' },
    { name: 'Ceres', value: 939, label: 'Ceres (a dwarf planet)' },
    { name: 'Enceladus', value: 504, label: 'Enceladus (Saturn’s moon)' },
  ],

  events: [
    { name: 'Vesuvius buries Pompeii', said: 'Vesuvius buried Pompeii in AD 79', year: 79 },
    { name: 'The Battle of Hastings', said: 'The Battle of Hastings was in 1066', year: 1066 },
    { name: 'Magna Carta is sealed', said: 'Magna Carta was sealed in 1215', year: 1215 },
    { name: 'The Black Death reaches Europe', said: 'The Black Death reached Europe in 1347', year: 1347 },
    { name: 'Constantinople falls', said: 'Constantinople fell in 1453', year: 1453 },
    { name: 'Columbus reaches the Americas', said: 'Columbus reached the Americas in 1492', year: 1492 },
    { name: 'Luther posts his 95 Theses', said: 'Luther posted his 95 Theses in 1517', year: 1517 },
    { name: 'The Mayflower lands', said: 'The Mayflower landed in 1620', year: 1620 },
    { name: 'Shakespeare’s First Folio is printed', said: 'The First Folio was printed in 1623', year: 1623 },
    { name: 'Harvard is founded', said: 'Harvard was founded in 1636', year: 1636 },
    { name: 'The Great Fire of London', said: 'The Great Fire of London was in 1666', year: 1666 },
    { name: 'Newton publishes the Principia', said: 'Newton published the Principia in 1687', year: 1687 },
    { name: 'The US Declaration of Independence', said: 'The Declaration of Independence was adopted in 1776', year: 1776 },
    { name: 'The storming of the Bastille', said: 'The Bastille was stormed in 1789', year: 1789 },
    { name: 'The Louisiana Purchase', said: 'The Louisiana Purchase was in 1803', year: 1803 },
    { name: 'The Battle of Waterloo', said: 'The Battle of Waterloo was in 1815', year: 1815 },
    { name: 'The California Gold Rush begins', said: 'The California Gold Rush began in 1848', year: 1848 },
    { name: 'Darwin publishes On the Origin of Species', said: 'On the Origin of Species came out in 1859', year: 1859 },
    { name: 'The American Civil War begins', said: 'The American Civil War began in 1861', year: 1861 },
    { name: 'The Suez Canal opens', said: 'The Suez Canal opened in 1869', year: 1869 },
    { name: 'Bell patents the telephone', said: 'Bell patented the telephone in 1876', year: 1876 },
    { name: 'Krakatoa erupts', said: 'Krakatoa erupted in 1883', year: 1883 },
    { name: 'The Statue of Liberty is dedicated', said: 'The Statue of Liberty was dedicated in 1886', year: 1886 },
    { name: 'The Eiffel Tower opens', said: 'The Eiffel Tower opened in 1889', year: 1889 },
    { name: 'The first modern Olympics', said: 'The first modern Olympics were in 1896', year: 1896 },
    { name: 'The first Nobel Prizes', said: 'The first Nobel Prizes were awarded in 1901', year: 1901 },
    { name: 'The Wright brothers’ first flight', said: 'The Wright brothers first flew in 1903', year: 1903 },
    { name: 'The Model T goes on sale', said: 'The Model T went on sale in 1908', year: 1908 },
    { name: 'The Mona Lisa is stolen from the Louvre', said: 'The Mona Lisa was stolen in 1911', year: 1911 },
    { name: 'The Titanic sinks', said: 'The Titanic sank in 1912', year: 1912 },
    { name: 'The Panama Canal opens', said: 'The Panama Canal opened in 1914', year: 1914 },
    { name: 'The Russian Revolution', said: 'The Russian Revolution was in 1917', year: 1917 },
    { name: 'The 19th Amendment gives US women the vote', said: 'The 19th Amendment was ratified in 1920', year: 1920 },
    { name: 'Fleming discovers penicillin', said: 'Fleming discovered penicillin in 1928', year: 1928 },
    { name: 'Pluto is discovered', said: 'Pluto was discovered in 1930', year: 1930 },
    { name: 'World War II ends', said: 'World War II ended in 1945', year: 1945 },
    { name: 'India becomes independent', said: 'India became independent in 1947', year: 1947 },
    { name: 'Everest is first climbed', said: 'Everest was first climbed in 1953', year: 1953 },
    { name: 'Sputnik is launched', said: 'Sputnik was launched in 1957', year: 1957 },
    { name: 'The Berlin Wall goes up', said: 'The Berlin Wall went up in 1961', year: 1961 },
    { name: 'The first Super Bowl', said: 'The first Super Bowl was played in 1967', year: 1967 },
    { name: 'The first Moon landing', said: 'The first Moon landing was in 1969', year: 1969 },
    { name: 'The Chernobyl disaster', said: 'The Chernobyl disaster was in 1986', year: 1986 },
    { name: 'The Berlin Wall falls', said: 'The Berlin Wall fell in 1989', year: 1989 },
    { name: 'The Hubble telescope is launched', said: 'Hubble was launched in 1990', year: 1990 },
    { name: 'The Channel Tunnel opens', said: 'The Channel Tunnel opened in 1994', year: 1994 },
    { name: 'Euro notes and coins arrive', said: 'Euro notes and coins arrived in 2002', year: 2002 },
    { name: 'The first iPhone goes on sale', said: 'The first iPhone went on sale in 2007', year: 2007 },
  ],

  people: [
    { name: 'Leonardo da Vinci', born: 1452 },
    { name: 'Michelangelo', born: 1475 },
    { name: 'William Shakespeare', born: 1564 },
    { name: 'Galileo Galilei', born: 1564 },
    { name: 'Johannes Kepler', born: 1571 },
    { name: 'Rembrandt', born: 1606 },
    { name: 'Johann Sebastian Bach', born: 1685 },
    { name: 'Benjamin Franklin', born: 1706 },
    { name: 'George Washington', born: 1732 },
    { name: 'Thomas Jefferson', born: 1743 },
    { name: 'Wolfgang Amadeus Mozart', born: 1756 },
    { name: 'Napoleon Bonaparte', born: 1769 },
    { name: 'Ludwig van Beethoven', born: 1770 },
    { name: 'Jane Austen', born: 1775 },
    { name: 'Abraham Lincoln', born: 1809 },
    { name: 'Charles Darwin', born: 1809 },
    { name: 'Charles Dickens', born: 1812 },
    { name: 'Ada Lovelace', born: 1815 },
    { name: 'Queen Victoria', born: 1819 },
    { name: 'Florence Nightingale', born: 1820 },
    { name: 'Leo Tolstoy', born: 1828 },
    { name: 'Mark Twain', born: 1835 },
    { name: 'Claude Monet', born: 1840 },
    { name: 'Thomas Edison', born: 1847 },
    { name: 'Vincent van Gogh', born: 1853 },
    { name: 'Nikola Tesla', born: 1856 },
    { name: 'Sigmund Freud', born: 1856 },
    { name: 'Marie Curie', born: 1867 },
    { name: 'Mahatma Gandhi', born: 1869 },
    { name: 'Winston Churchill', born: 1874 },
    { name: 'Albert Einstein', born: 1879 },
    { name: 'Pablo Picasso', born: 1881 },
    { name: 'Coco Chanel', born: 1883 },
    { name: 'Charlie Chaplin', born: 1889 },
    { name: 'Agatha Christie', born: 1890 },
    { name: 'Amelia Earhart', born: 1897 },
    { name: 'Walt Disney', born: 1901 },
    { name: 'Frida Kahlo', born: 1907 },
    { name: 'Alan Turing', born: 1912 },
    { name: 'Rosa Parks', born: 1913 },
    { name: 'Nelson Mandela', born: 1918 },
    { name: 'Marilyn Monroe', born: 1926 },
    { name: 'Martin Luther King Jr.', born: 1929 },
    { name: 'Anne Frank', born: 1929 },
    { name: 'Jane Goodall', born: 1934 },
    { name: 'Elvis Presley', born: 1935 },
    { name: 'John Lennon', born: 1940 },
    { name: 'Stephen Hawking', born: 1942 },
    { name: 'Steve Jobs', born: 1955 },
    { name: 'Bill Gates', born: 1955 },
    { name: 'Barack Obama', born: 1961 },
  ],

  elements: [
    { name: 'Hydrogen', z: 1 },
    { name: 'Helium', z: 2 },
    { name: 'Lithium', z: 3 },
    { name: 'Carbon', z: 6 },
    { name: 'Nitrogen', z: 7 },
    { name: 'Oxygen', z: 8 },
    { name: 'Fluorine', z: 9 },
    { name: 'Neon', z: 10 },
    { name: 'Sodium', z: 11 },
    { name: 'Magnesium', z: 12 },
    { name: 'Aluminium', z: 13 },
    { name: 'Silicon', z: 14 },
    { name: 'Phosphorus', z: 15 },
    { name: 'Sulfur', z: 16 },
    { name: 'Chlorine', z: 17 },
    { name: 'Argon', z: 18 },
    { name: 'Potassium', z: 19 },
    { name: 'Calcium', z: 20 },
    { name: 'Titanium', z: 22 },
    { name: 'Chromium', z: 24 },
    { name: 'Iron', z: 26 },
    { name: 'Cobalt', z: 27 },
    { name: 'Nickel', z: 28 },
    { name: 'Copper', z: 29 },
    { name: 'Zinc', z: 30 },
    { name: 'Arsenic', z: 33 },
    { name: 'Bromine', z: 35 },
    { name: 'Krypton', z: 36 },
    { name: 'Silver', z: 47 },
    { name: 'Tin', z: 50 },
    { name: 'Iodine', z: 53 },
    { name: 'Xenon', z: 54 },
    { name: 'Tungsten', z: 74 },
    { name: 'Platinum', z: 78 },
    { name: 'Gold', z: 79 },
    { name: 'Mercury', z: 80 },
    { name: 'Lead', z: 82 },
    { name: 'Radon', z: 86 },
    { name: 'Radium', z: 88 },
    { name: 'Uranium', z: 92 },
    { name: 'Plutonium', z: 94 },
  ],
};
